spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Path=/hello
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 49.235.32.38:8848
  application:
    name: gulimall-gateway

server:
  port: 8889